### ISSUE TITLE
USER STORY: PAGES : Home Page

### ISSUE THREAD

**Issue by arthurmezaonik** [arthurmezaonik/portfolio_project_04#10]
# DESCRIPTION
As a **Site User** I can **land on a home page** so that **I can understand what is the website about**.

# ACCEPTANCE CRITERIA
1. Land in a home page

# TASKS
- [x] Create home page template
- [x] Create home page URL
- [x] Create home page view
