### ISSUE TITLE
USER STORY: PAGES : Job List Page

### ISSUE THREAD

**Issue by arthurmezaonik** [arthurmezaonik/portfolio_project_04#11]
# DESCRIPTION
As a **Site User** I can **land in a page that contains all the published jobs** so that **I can choose the one that I want**.

# ACCEPTANCE CRITERIA
1. Land in a webpage that have all the posted jobs
2. Be able to filter the jobs based on the job type

# TASKS
- [x] Create page template
- [x] Create page view
- [x] Create page URL
- [x] Create filter
