### ISSUE TITLE
USER STORY: USER PAGE: Manage Created Jobs

### ISSUE THREAD

**Issue by arthurmezaonik** [arthurmezaonik/portfolio_project_04#12]
# DESCRIPTION
As a **Site User** I can **have access tomy created jobs** so that **I can manage (edit / delete) it**.

# ACCEPTANCE CRITERIA
1. Able to check all the user's created jobs
2. User be able to modify the job
3. User be able to delete the job

# TASKS
- [x] Create page template
- [x] Create page URL
- [x] Create page view
- [x] Add CRUD functionalities
