### ISSUE TITLE
USER STORY: <EPIC TITLE>: <TITLE>

### ISSUE THREAD

**Issue by arthurmezaonik** [arthurmezaonik/portfolio_project_04#9]
# DESCRIPTION
As a **Site User** I can **view a list of future classes** so that **I can register on it**

# ACCEPTANCE CRITERIA
1. View a list of future classes on the home page

# TASKS
- [ ] Create Classes app
- [ ] Create Classes db
- [ ] Shown classes on the home page
